### ISSUE TITLE
`m.config.variant = package_variants[0]  IndexError: list index out of range`

### ISSUE THREAD

**Issue by hadim** [prefix-dev/rattler-build-conda-compat#58]
I am seeing the same issue as reported in https://github.com/prefix-dev/rattler-build-conda-compat/issues/56 but I am not sure if this is the same cause (re-rendering locally versus validating in CI).

I tried applying the proposed patch: `m.config.variant = package_variants[0] if package_variants else []` but then I get a new error in conda-build: `subdir = self.variant.get("target_platform", self.build_subdir) AttributeError: 'list' object has no attribute 'get'`

I tried diving a bit in the variant config code, but it's too convoluted for me to understand what is going on there.

Any idea?

**Comment by hadim** [comment]
Potential fix at https://github.com/prefix-dev/rattler-build-conda-compat/pull/59

**Comment by wolfv** [comment]
Should we close this until it comes back up again?
